gui/portal/pages/views.py
# -*- coding: utf-8 -*-
'''
Created on Dec/2016

@author: Zilton Cordeiro Junior
@github: https://github.com/zilton
@project: EUBRA-BIGSEA
@task: Active Learning System
'''

import ast
from bson import json_util
from datetime import datetime
from dateutil import tz
import datetime
from django.template.defaultfilters import pprint
from flask import (
    Blueprint, render_template, session, g, flash, request, redirect, url_for,
    current_app
)
from flask import Blueprint, render_template
import re
import time

from accounts.models import User
from pages.models import Statistic
from pages.models import Tweets
from settings import MONGODB_SETTINGS, db_active_learning
from settings_active_self_learning import MIN_SCORE_SELF_TRAINING
from system.models import Project

pages_app = Blueprint('pages_app', __name__)

t = None

@pages_app.route('/')
def index():   
    return render_template('pages/index.html')


@pages_app.route('/about/')
def about():
    return render_template('pages/about.html')

@pages_app.route('/training/<project_name>')
def training(project_name):
    if 'user_id' in session:
        user = User.objects.get(pk=session['user_id'])
        if user.control:
            if not project_name in user.control.projects:
                g.tweet = None
                flash(u"You don't have permission to work on the project %s" % project_name, 'warning')
                return redirect("/")
        else:
            flash(u"You don't have permission to work on the project %s" % project_name, 'warning')
            return redirect("/")
        
        project = Project.objects.get(name=project_name)
        if not project.is_active:
            g.tweet = None
            flash(u"The %s project is disabled!" % project_name, 'warning')
            return render_template('pages/training.html')
        
        g.tweet = Tweets.objects.filter(__raw__={'control.lock' : {'$exists' : False}, 'control.project':project_name}).order_by('control.created_at', 'age').first()
        
        try:
            tweet_utc_time = g.tweet.created_at
            
            from_zone = tz.tzutc()
            to_zone = tz.tzlocal()
            
            utc = g.tweet.created_at.replace(tzinfo=from_zone)
            local = utc.astimezone(to_zone)
            print utc, local
            g.tweet.created_at = local
            
            conn = db_active_learning['tweets']
            control = g.tweet.control
            control['lock'] = datetime.datetime.utcnow()
            conn.save({'_id':int(g.tweet._id), 'control':control, 'text':g.tweet.text, 'created_at':tweet_utc_time})
            
            g.statistic = Statistic.objects.filter(username=g.user.username).first()
        except:
            g.tweet = None
        
        if not g.tweet == None:
            '''
            #SERÁ NECESSÁRIO NO FUTURO
            while (True) :
                print g.tweet.control
                control = ast.literal_eval(str(g.tweet.control))
                if 'score' in control['self_training']:
                    if control['classification']['score'] < MIN_SCORE_SELF_TRAINING:
                        break
                g.tweet = Tweets.objects.filter(control__exists={"active_learning" : {}}).first()
            '''
            
            g.class_color = []
            project = Project.objects.get(name=project_name)
            for train in project.workflow.trains:
                for i in range(0, len(train.classes)):
                    g.class_color.append([train.classes[i], train.colors[i]])
            
            g.metrics = ['Classifier', 'Score', 'Sentiment']
            g.values = []
            g.project = project_name
            
            for classifier in g.tweet["control"]["classification"]:
                g.values.append([classifier["classifier"],
                                 float("%.2f" % classifier["score"]),
                                 classifier["sentiment"]])
    else:
        return redirect('login')
    
    return render_template('pages/training.html')

@pages_app.route('/projects/')
def all_projects():
    projects = Project.objects.filter()
    
    if 'user_id' in session:
        user = User.objects.get(pk=session['user_id'])
        
        if user.control:
            if user.control.projects:
                user_projects = user.control.projects
            else:
                user_projects = []
        else:
            user.add_control()
            
        g.all_projects = []
        
        for project in projects:
            if project.is_active:
                if project.name in user_projects:
                    g.all_projects.append([project.name, True])
                else:
                    g.all_projects.append([project.name, False])
    
    return render_template('pages/projects.html')
    
@pages_app.route('/projects/action/<project>/<action>')
def add_remove_project(project, action):
    print project, action
    
    if action.lower() == "true":
        action = True
    elif action.lower() == "false":
        action = False
    else:
        return redirect(url_for('pages_app.all_projects'))
    
    if 'user_id' in session:
        user = User.objects.get(pk=session['user_id'])
        if user.control:
            if not user.control.projects:
                user.add_control()
            
        else:
            user.add_control()
        
        
        if action:
            if not project in user.control.projects:
                user.control.projects.append(project)
        else:
            if project in user.control.projects:
                user.control.projects.remove(project)
                
        user.save() 
    
    return redirect(url_for('pages_app.all_projects'))

@pages_app.route('/statistics/')
def statistics():
    '''
    db.training_tweets.aggregate([ { "$group": { "_id": { "day": { "$dayOfMonth" : "$control.active_learning.classified_at" }, "month": { "$month" : "$control.active_learning.classified_at" }, "year": { "$year" : "$control.active_learning.classified_at" } }, "Count": { "$sum" : 1 } } }, { "$sort": { "_id.year": 1, "_id.month": 1, "_id.day": 1 } }, { "$project": { "_id": 0, "date": { "$concat": [ {"$substr" : [ "$_id.day", 0, 2]}, "-", {"$substr" : [ "$_id.month", 0, 2]}, "-", {"$substr" : [ "$_id.year", 0, 4]} ] }, "count": 1 } } ])
    '''
    
    g.user = None
    g.count_data = [{"key" : "Labeled tweets", "values":[], "color": "#00adff"}]
    if 'user_id' in session:
        try:
            g.user = User.objects.get(pk=session['user_id'])
            if g.user.is_superuser:
                collection_training_tweets = db_active_learning['training_tweets']
                result = collection_training_tweets.aggregate([ { "$group": {
                                                                             "_id": {
                                                                                     "day": {"$dayOfMonth" : "$control.active_learning.classified_at" },
                                                                                     "month": { "$month" : "$control.active_learning.classified_at" },
                                                                                     "year": { "$year" : "$control.active_learning.classified_at" } 
                                                                                     },
                                                                             "count": { "$sum" : 1 } } },
                                                               { "$sort": {
                                                                           "_id.day": -1,
                                                                           "_id.year": -1,
                                                                           "_id.month": -1,
                                                                            } 
                                                                }, 
                                                               { "$project": { 
                                                                              "_id": 0, 
                                                                              "date": { 
                                                                                       "$concat": [ 
                                                                                                   {
                                                                                                     "$substr" : [ "$_id.day", 0, 2]}, 
                                                                                                   "-", {"$substr" : [ "$_id.month", 0, 2]}, 
                                                                                                   "-", {"$substr" : [ "$_id.year", 0, 4]} ] }, 
                                                                              "count": 1 
                                                                              } 
                                                                } ])
                i = 0
                for r in result:
                    #date = time.mktime(datetime.datetime.strptime(r['date'], "%d-%m-%Y").timetuple())
                    #g.count_data[0]["values"].append([int(date)*1000, r['count']])
                    g.count_data[0]["values"].append({"label" : str(r['date']), "value" : int(r['count'])})
                    i += 1
                    if i == 15:
                        break

        except:
            pass
    
    return render_template('pages/statistics.html')

@pages_app.route('/manager/system', methods=['GET', 'POST'])
def manager_system():
    
    if 'user_id' in session:
        pass
    
    return render_template('pages/manager_system.html')

@pages_app.route('/classification/<sentiment>/<_id>')
def classification(sentiment, _id):
    
    if not 'user_id' in session:

gui/portal/templates/pages/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}

	<div class="row-fluid">
  	<div class="span12">
  		<legend><font color="#676767">About</font></legend>
  		<p align="justify">
  			<font size="3" color="#111111">
  				  Supervised learning is the machine learning task of inferring a function from labeled training data.
				  <br/><br/>
				  The training data consist of a set of training examples. 
				  In supervised learning, each example is a pair consisting of an input object (typically a vector) 
				  and a desired output value (also called the supervisory signal).
				  <br/><br/>
				  A supervised learning algorithm analyzes the training data and produces an inferred function, which 
				  can be used for mapping new examples. An optimal scenario will allow for the algorithm to correctly determine 
				  the class labels for unseen instances. This requires the learning algorithm to generalize from the training data
				   to unseen situations in a "reasonable" way.</br></br>
				  Active learning Instead of assuming that all of the training examples are given at the start, 
				  active learning algorithms interactively collect new examples, typically by making queries to a human user. 
				  Often, the queries are based on unlabeled data, which is a scenario that combines semi-supervised learning with 
				  active learning.
				  <br/><br/>
  			</font>
  		</p>
  		
  	</div>
  </div>
  
  <h6>This system was developed by the EUBRA-BIGSEA team from UFMG.</h6></br>

{% endblock %}

gui/portal/templates/pages/index.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}

  {% if g.user %}
  <h3>Welcome, {{ g.user.name }}!</h3>
  
  
  <div class="row-fluid">
  	<div class="span12">
  		<legend><font color="#676767">Overview</font></legend>
  		<p align="justify">
  			<font size="3" color="#111111">
  				In this system you have access to the EUBRA-BIGSEA LAC Active Learning and Self-training.</br>
  				The main purpose of the system is to enable the creation of more accurate databases for classification 
  				and/or sentiment analysis in Twitter messages. If you are an administrator, the system will allow you to 
  				create a new project, with no need for any training for LAC classifier. 
  				The system was built to work in real-time data flow, ensuring that the LAC classifier evolves according 
  				to the dynamics of each project.
  			</font>
  		</p>
  		<legend><font color="#676767">Projects</font></legend>
  		<p align="justify">
  			<font size="3" color="#111111">
  				It is necessary to have a collection of data in mongodb to initialize the system. 
  				The messages displayed to the user are selected based on the evolution of the LAC classifier, 
  				which is measured according to the amount of rules generated. 
  				A message that generated the least amount of rules in a 150-size window is selected. 
  				It is possible to set the number of classes, N-grams size, stemming, stop words, language and 
  				with respect to self-training it is possible to determine the threshold  (accuracy) for a message to be 
  				inserted directly into the LAC classifier training, without the need to be presented for user labeling.
  			</font>
  		</p>
  		<legend><font color="#676767">Background</font></legend>
  		<p align="justify">
  			<font size="3" color="#111111">
  				All processes are initialized and stopped automatically. 
  				The system allows the administrator to configure all the parameters referring to the projects 
  				that he is registered, activate and deactivate a project, manage the users and follow the statistics 
  				of the projects and use of the system by the users.
  			</font>
  		</p>
  	</div>
  </div>
  
  {% else %}
  <h3>Welcome, Guest!</h3>
  <h5>To use the Active Learning System, please login.</h5>
  {% endif%}
  	<br />
	<br />
	<br />
	<br />
  
  

{% endblock %}

gui/portal/templates/pages/manager_system.html
{% extends 'base.html' %} {% block title %}Information{% endblock %}
{%block content %}
<head>
<meta charset="utf-8" />
<link rel="stylesheet" href="/static/data/nv.d3.css" />
<script src="/static/data/d3.min.js"></script>
<script src="/static/data/nv.d3.js"></script>
<!-- 
<style>
#chart svg {
	height: 400px;
}
</style>
</head>

<div id="chart">
	<svg>


	<script>
	data = [{'color': '#008000', 'key': 'Labeled_data', 'values': [[1479002400000, 100], [1479088800000, 135], [1479175200000, 267], [1479261600000, 69], [1479348000000, 172], [1479434400000, 28], [1479693600000, 32]]}];
	
		  nv.addGraph(function() {
		      var chart = nv.models.linePlusBarChart()
		            .margin({top: 30, right: 60, bottom: 50, left: 70})
		            //We can set x data accessor to use index. Reason? So the bars all appear evenly spaced.
		            .x(function(d,i) { return i })
		            .y(function(d,i) {return d[1] })
		            ;

		      chart.xAxis.tickFormat(function(d) {
		        var dx = data[0].values[d] && data[0].values[d][0] || 0;
		        return d3.time.format('%x')(new Date(dx))
		      });

		      chart.y1Axis
		          .tickFormat(d3.format(',f'));

		      chart.y2Axis
		          .tickFormat(function(d) { return '' + d3.format(',f')(d) });

		      chart.bars.forceY([0]);

		      d3.select('#chart svg')
		        .datum(data)
		        .transition()
		        .duration(0)
		        .call(chart);

		      nv.utils.windowResize(chart.update);

		      return chart;
		  });</script>
	</svg>
</div>

 -->
<style>
#chart svg {
	height: 400px;
}
</style>


<div id="chart">
	<svg>	</svg>
</div>

	<script>
	data = {{g.count_data | safe}};
	nv.addGraph(function() {
		  var chart = nv.models.multiBarHorizontalChart()
		      .x(function(d) { return d.label })
		      .y(function(d) { return d.value })
		      .margin({top: 30, right: 20, bottom: 50, left: 175})
		      .showValues(true)
		      .showControls(false);

		  chart.yAxis
		      .tickFormat(d3.format(',.2f'));

		  d3.select('#chart svg')
		      .datum(data)
		    .transition().duration(500)
		      .call(chart);

		  nv.utils.windowResize(chart.update);

		  return chart;
		});
	</script>

{% endblock %}

gui/portal/templates/pages/projects.html
{% extends 'base.html' %}
{% block title %}Information{% endblock %}
{%block content %}
	{% if g.user %}
		
			  <h1><font color="#00adff">Projects</font></h1>
			  <br/><br/>
			  <font size=4>
			  
					{% for proj in g.all_projects %}
					<ul style="list-style-type:none"></ul>
				  		<div class='row'>
							<div class='span2'>
					  			<li>{{proj[0]}}</li>
					  		</div>
					  		<div class="span2"></div>
							<div class='span8'>
					  			<a href="{{url_for('pages_app.add_remove_project', project=proj[0], action=not proj[1]) }}">
									{% if proj[1] %}
										<input type="image" src="/static/img/project_delete.ico" style="width:4%;" value={{proj[1]}} title="Remove project {{proj[0]}} from your project list.">
									{% else %}
										<input type="image" src="/static/img/project_add.ico" style="width:4%;" value={{proj[1]}} title="Add project {{proj[0]}} to your project list.">
									{% endif %}
								</a>
								
							</div>
						</div>
						</br>
					</ul>
			  		{% endfor %}
			  </font>
			  </br>
			  </br>
			  </br>
			  </br>
			  
			  <!-- 
			  <strong>Name: </strong>{{g.user.name}}<br/><br/>
			  <strong>Email: </strong>{{g.user.email}}<br/><br/>
			  <strong>Institution: </strong>{{g.user.institution}}<br/><br/>
			  <strong>Username: </strong>{{g.user.username}}<br/><br/>
			  <a href="https://en.gravatar.com/gravatars/new/computer" target="_blank"><button type="button" class="btn btn-primary">Change photo</button></a><br/><br/>
			  <a href="/recover-password"><button type="button" class="btn btn-primary">Change password</button></a><br/><br/>
			  <a href="/recover-password"><button type="button" class="btn btn-primary">Request admin privileges</button></a><br/><br/>
			  <br/><br/>
			  <br/><br/> -->
	
	{% endif%}
{% endblock %}

gui/portal/templates/pages/statistics.html
{% extends 'base.html' %} {% block title %}Information{% endblock %}
{%block content %}
<head>
<meta charset="utf-8" />
<link rel="stylesheet" href="/static/data/nv.d3.css" />
<script src="/static/data/d3.min.js"></script>
<script src="/static/data/nv.d3.js"></script>
<!-- 
<style>
#chart svg {
	height: 400px;
}
</style>
</head>

<div id="chart">
	<svg>


	<script>
	data = [{'color': '#008000', 'key': 'Labeled_data', 'values': [[1479002400000, 100], [1479088800000, 135], [1479175200000, 267], [1479261600000, 69], [1479348000000, 172], [1479434400000, 28], [1479693600000, 32]]}];
	
		  nv.addGraph(function() {
		      var chart = nv.models.linePlusBarChart()
		            .margin({top: 30, right: 60, bottom: 50, left: 70})
		            //We can set x data accessor to use index. Reason? So the bars all appear evenly spaced.
		            .x(function(d,i) { return i })
		            .y(function(d,i) {return d[1] })
		            ;

		      chart.xAxis.tickFormat(function(d) {
		        var dx = data[0].values[d] && data[0].values[d][0] || 0;
		        return d3.time.format('%x')(new Date(dx))
		      });

		      chart.y1Axis
		          .tickFormat(d3.format(',f'));

		      chart.y2Axis
		          .tickFormat(function(d) { return '' + d3.format(',f')(d) });

		      chart.bars.forceY([0]);

		      d3.select('#chart svg')
		        .datum(data)
		        .transition()
		        .duration(0)
		        .call(chart);

		      nv.utils.windowResize(chart.update);

		      return chart;
		  });</script>
	</svg>
</div>

 -->
<style>
#chart svg {
	height: 400px;
}
</style>


<div id="chart">
	<svg>	</svg>
</div>

	<script>
		data = {{g.count_data | safe}};
		nv.addGraph(function() {
			  var chart = nv.models.multiBarHorizontalChart()
			      .x(function(d) { return d.label })
			      .y(function(d) { return d.value })
			      .margin({top: 30, right: 20, bottom: 50, left: 175})
			      .showValues(true)
			      .showControls(false);
	
			  chart.yAxis
			      .tickFormat(d3.format(',.2f'));
	
			  d3.select('#chart svg')
			      .datum(data)
			    .transition().duration(500)
			      .call(chart);
	
			  nv.utils.windowResize(chart.update);
	
			  return chart;
			});
	</script>
	</br>
	</br>
	</br>
	</br>

{% endblock %}

gui/portal/templates/pages/training.html
{% extends 'base.html' %} {% block title %}Training{% endblock %} {%
block content %} {% if g.user %} {% if g.tweet %}
<center>
	<div class='row'>
		<div class='span2'></div>
		<div class='span8' style='padding: 100px 50px 50px 50px;'>
			<div class="well well-small">
				<div title="Label this tweet.">
					<h2>{{ g.tweet.text }}</h2>
					<h5 class="panel-title">
						<p align=right>{{ g.tweet.created_at }}</p>
					</h5>
				</div>
				
				{% for item in g.class_color %}
					<a
						href="{{url_for('pages_app.classification', sentiment=item[0]+';'+g.project, _id=g.tweet._id) }}">
						<button class="btn btn-default" style="background:#{{item[1]}}" type="button" name="submit" value="{{item[0]}}">
						&nbsp;
						</button>
						<span>{{item[0]}}</span>
						&nbsp;&nbsp;&nbsp;
						<!-- <input style ="background-color:#{{item[1]}}" type="submit" name="submit" value={{item[0]}}> -->
					</a>
				{% endfor %}
				<!-- 
				<a
					href="{{url_for('pages_app.classification', sentiment='positive', _id=g.tweet._id) }}">
					<input class="btn btn-success" type="submit" name="submit" value="Positive">
				</a>
				<a
					href="{{url_for('pages_app.classification', sentiment='neutral', _id=g.tweet._id) }}">
					<input class="btn btn-primary" type="submit" name="submit" value="Neutral">
				</a>
				<a
					href="{{url_for('pages_app.classification', sentiment='negative', _id=g.tweet._id) }}">
					<input class="btn btn-danger" type="submit" name="submit" value="Negative">
				</a>
				 -->
			</div>
			<!-- 
			<div style='border: 2px solid rgba(10, 10, 10, 0.1);'>
				<h3 class="panel-title">
					<p align=center><font color="#00adff"><b>Automatic classification</p></b></font>
				</h3>
				-->
				<span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
				<table class="table table-striped">
					<thead>
						<tr>
							{% for metric in g.metrics %}
							<th>
								<center>{{metric}}</center>
							</th> {% endfor %}
						</tr>
					</thead>

					<tbody>
						<tr>
							{% for classifier in g.values %} {% for value in classifier %} {%
							if value == "positive" %}
							<td><center>
									<font color="green"><b>{{value}}</b></font>
								</center></td>
							{% elif value == "negative" %}
							<td><center>
									<font color="red"><b>{{value}}</b></font>
								</center></td>
							{% elif value == "neutral" %}
							<td><center>
									<font color="#00adff"><b>{{value}}</b></font>
								</center></td>
							{% elif value == "LAC" %}
							<td><center>
									<font color="#005882"><b>{{value}}</b></font>
								</center></td>
							{% else %}
							<td>
								<center>{{value}}</center>
							</td> {% endif%} {% endfor %} {% endfor %}
						</tr>
					</tbody>
				</table>
			<!-- </div>-->
     
			<br />
			<br />
			<!-- <h3 class="panel-title"><p align=center>Text to be classified</p></h3> -->


		</div>
	</div>
</center>

{% else %}
<center>
	<h3>Sorry, we don't have tweets for classification.</h3>
	<br />
	<br />
	<br />
	<br />
</center>
{% endif%} {% else %}
<meta http-equiv="refresh"
	content="0; url={{ url_for('accounts_app.login') }}" />
	
<script src="jscolor.js"></script>

{% endif%} {% endblock %}