gui/portal/pages/views.py
# -*- coding: utf-8 -*-
'''
Created on Dec/2016

@author: Zilton Cordeiro Junior
@github: https://github.com/zilton
@project: EUBRA-BIGSEA
@task: Active Learning System
'''

import ast
from bson import json_util
from datetime import datetime
from dateutil import tz
import datetime
from django.template.defaultfilters import pprint
from flask import (
    Blueprint, render_template, session, g, flash, request, redirect, url_for,
    current_app
)
from flask import Blueprint, render_template
import re
import time

from accounts.models import User
from pages.models import Statistic
from pages.models import Tweets
from settings import MONGODB_SETTINGS, db_active_learning
from settings_active_self_learning import MIN_SCORE_SELF_TRAINING
from system.models import Project

pages_app = Blueprint('pages_app', __name__)

t = None

@pages_app.route('/')
def index():   
    return render_template('pages/index.html')


@pages_app.route('/about/')
def about():
    return render_template('pages/about.html')

@pages_app.route('/training/<project_name>')
def training(project_name):
    if 'user_id' in session:
        user = User.objects.get(pk=session['user_id'])
        if user.control:
            if not project_name in user.control.projects:
                g.tweet = None
                flash(u"You don't have permission to work on the project %s" % project_name, 'warning')
                return redirect("/")
        else:
            flash(u"You don't have permission to work on the project %s" % project_name, 'warning')
            return redirect("/")
        
        project = Project.objects.get(name=project_name)
        if not project.is_active:
            g.tweet = None
            flash(u"The %s project is disabled!" % project_name, 'warning')
            return render_template('pages/training.html')
        
        g.tweet = Tweets.objects.filter(__raw__={'control.lock' : {'$exists' : False}, 'control.project':project_name}).order_by('control.created_at', 'age').first()
        
        try:
            tweet_utc_time = g.tweet.created_at
            
            from_zone = tz.tzutc()
            to_zone = tz.tzlocal()
            
            utc = g.tweet.created_at.replace(tzinfo=from_zone)
            local = utc.astimezone(to_zone)
            print utc, local
            g.tweet.created_at = local
            
            conn = db_active_learning['tweets']
            control = g.tweet.control
            control['lock'] = datetime.datetime.utcnow()
            conn.save({'_id':int(g.tweet._id), 'control':control, 'text':g.tweet.text, 'created_at':tweet_utc_time})
            
            g.statistic = Statistic.objects.filter(username=g.user.username).first()
        except:
            g.tweet = None
        
        if not g.tweet == None:
            '''
            #SERÁ NECESSÁRIO NO FUTURO
            while (True) :
                print g.tweet.control
                control = ast.literal_eval(str(g.tweet.control))
                if 'score' in control['self_training']:
                    if control['classification']['score'] < MIN_SCORE_SELF_TRAINING:
                        break
                g.tweet = Tweets.objects.filter(control__exists={"active_learning" : {}}).first()
            '''
            
            g.class_color = []
            project = Project.objects.get(name=project_name)
            for train in project.workflow.trains:
                for i in range(0, len(train.classes)):
                    g.class_color.append([train.classes[i], train.colors[i]])
            
            g.metrics = ['Classifier', 'Score', 'Sentiment']
            g.values = []
            g.project = project_name
            
            for classifier in g.tweet["control"]["classification"]:
                g.values.append([classifier["classifier"],
                                 float("%.2f" % classifier["score"]),
                                 classifier["sentiment"]])
    else:
        return redirect('login')
    
    return render_template('pages/training.html')

@pages_app.route('/projects/')
def all_projects():
    projects = Project.objects.filter()
    
    if 'user_id' in session:
        user = User.objects.get(pk=session['user_id'])
        
        if user.control:
            if user.control.projects:
                user_projects = user.control.projects
            else:
                user_projects = []
        else:
            user.add_control()
            
        g.all_projects = []
        
        for project in projects:
            if project.is_active:
                if project.name in user_projects:
                    g.all_projects.append([project.name, True])
                else:
                    g.all_projects.append([project.name, False])
    
    return render_template('pages/projects.html')
    
@pages_app.route('/projects/action/<project>/<action>')
def add_remove_project(project, action):
    print project, action
    
    if action.lower() == "true":
        action = True
    elif action.lower() == "false":
        action = False
    else:
        return redirect(url_for('pages_app.all_projects'))
    
    if 'user_id' in session:
        user = User.objects.get(pk=session['user_id'])
        if user.control:
            if not user.control.projects:
                user.add_control()
            
        else:
            user.add_control()
        
        
        if action:
            if not project in user.control.projects:
                user.control.projects.append(project)
        else:
            if project in user.control.projects:
                user.control.projects.remove(project)
                
        user.save() 
    
    return redirect(url_for('pages_app.all_projects'))

@pages_app.route('/statistics/')
def statistics():
    '''
    db.training_tweets.aggregate([ { "$group": { "_id": { "day": { "$dayOfMonth" : "$control.active_learning.classified_at" }, "month": { "$month" : "$control.active_learning.classified_at" }, "year": { "$year" : "$control.active_learning.classified_at" } }, "Count": { "$sum" : 1 } } }, { "$sort": { "_id.year": 1, "_id.month": 1, "_id.day": 1 } }, { "$project": { "_id": 0, "date": { "$concat": [ {"$substr" : [ "$_id.day", 0, 2]}, "-", {"$substr" : [ "$_id.month", 0, 2]}, "-", {"$substr" : [ "$_id.year", 0, 4]} ] }, "count": 1 } } ])
    '''
    
    g.user = None
    g.count_data = [{"key" : "Labeled tweets", "values":[], "color": "#00adff"}]
    if 'user_id' in session:
        try:
            g.user = User.objects.get(pk=session['user_id'])
            if g.user.is_superuser:
                collection_training_tweets = db_active_learning['training_tweets']
                result = collection_training_tweets.aggregate([ { "$group": {
                                                                             "_id": {
                                                                                     "day": {"$dayOfMonth" : "$control.active_learning.classified_at" },
                                                                                     "month": { "$month" : "$control.active_learning.classified_at" },
                                                                                     "year": { "$year" : "$control.active_learning.classified_at" } 
                                                                                     },
                                                                             "count": { "$sum" : 1 } } },
                                                               { "$sort": {
                                                                           "_id.day": -1,
                                                                           "_id.year": -1,
                                                                           "_id.month": -1,
                                                                            } 
                                                                }, 
                                                               { "$project": { 
                                                                              "_id": 0, 
                                                                              "date": { 
                                                                                       "$concat": [ 
                                                                                                   {
                                                                                                     "$substr" : [ "$_id.day", 0, 2]}, 
                                                                                                   "-", {"$substr" : [ "$_id.month", 0, 2]}, 
                                                                                                   "-", {"$substr" : [ "$_id.year", 0, 4]} ] }, 
                                                                              "count": 1 
                                                                              } 
                                                                } ])
                i = 0
                for r in result:
                    #date = time.mktime(datetime.datetime.strptime(r['date'], "%d-%m-%Y").timetuple())
                    #g.count_data[0]["values"].append([int(date)*1000, r['count']])
                    g.count_data[0]["values"].append({"label" : str(r['date']), "value" : int(r['count'])})
                    i += 1
                    if i == 15:
                        break

        except:
            pass
    
    return render_template('pages/statistics.html')

@pages_app.route('/manager/system', methods=['GET', 'POST'])
def manager_system():
    
    if 'user_id' in session:
        pass
    
    return render_template('pages/manager_system.html')

@pages_app.route('/classification/<sentiment>/<_id>')
def classification(sentiment, _id):
    
    if not 'user_id' in session:

gui/portal/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{% block title %}{% endblock %} - BIGSEA Active Learning
	System</title>
<link rel="icon" href="/static/img/ufmg.png" type="image/x-icon">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description"
	content="{% block head_description %}{% endblock %}">
<meta name="author" content="{% block head_author %}{% endblock %}">

<!-- Le styles -->
<link
	href="{{ url_for('static', filename='bootstrap/css/cerulean.css') }}"
	rel="stylesheet">
<style>
body {
	padding-top: 60px;
	/* 60px to make the container go all the way to the bottom of the topbar */
}
</style>
<link
	href="{{ url_for('static', filename='bootstrap/css/bootstrap-responsive.css') }}"
	rel="stylesheet">

<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
  <script src="{{ url_for('static', filename='bootstrap/js/html5shiv.js') }}"></script>
  <![endif]-->
{% block extrahead %}{% endblock %}
</head>

<body>

	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">

				<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
				<a class="btn btn-navbar" data-toggle="collapse"
					data-target=".nav-collapse"> <span class="icon-bar"></span> <span
					class="icon-bar"></span> <span class="icon-bar"></span>
				</a>

				<!-- Be sure to leave the brand out there if you want it shown -->


				<!-- Everything you want hidden at 940px or less, place within here -->
				<div class="nav-collapse collapse">
					<!-- .nav, .navbar-search, .navbar-form, etc -->
					<ul class="nav">
						<li><a href="/">Home</a></li>
						<li><a href="{{ url_for('pages_app.about') }}">About</a></li>
					</ul>

					{% if g.user %}
					<ul class="nav">
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"> Training <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li class="dropdown-header">Projects</li>
							{% for project in g.projects %}
									<li><a href="{{ url_for('pages_app.training', project_name=project) }}">{{project}}</a></li>
							{% endfor %}
						</ul>
						</li>
					</ul>

					<ul class="nav">
						<li><a href="{{ url_for('pages_app.statistics') }}">Statistics</a>
						</li>
					</ul>
					{% if g.user.is_superuser %}
						<ul class="nav">
							<li><a href="{{ url_for('pages_app.all_projects') }}">Projects</a>
							</li>
						</ul>
						<ul class="nav">
							<li class="dropdown"><a href="#" class="dropdown-toggle"
								data-toggle="dropdown"> Manager <b class="caret"></b>
							</a>
								<ul class="dropdown-menu">
									<li><a href="{{ url_for('accounts_app.manager_user') }}">Users</a>
									</li>
									<li><a href="{{ url_for('system_app.new_project') }}">New
											project</a></li>
									<li><a href="{{ url_for('system_app.load_project') }}">Update
											project</a></li>
									<li><a href="{{ url_for('system_app.del_page') }}">Delete
											project</a></li>
								</ul></li>
						</ul>
					{% else %}
						<ul class="nav">
							<li><a href="{{ url_for('pages_app.all_projects') }}">Projects</a>
							</li>
						</ul>
					{% endif %}
					<ul class="nav pull-right">
						<li class="dropdown"><a href="#" class="dropdown-toggle"
							data-toggle="dropdown"> {{ g.user.username }} <b
								class="caret"></b>
						</a>
							<ul class="dropdown-menu">
								<li><a href="{{ url_for('accounts_app.information') }}">Information</a>
								</li>
								<li><a
									href="{{ url_for('accounts_app.recover_password') }}">Change
										password</a></li>
								<li><a href="{{ url_for('accounts_app.logout') }}">Logout</a>
								</li>
							</ul></li>
						<li><img src="https://www.gravatar.com/avatar/{{g.hash}}"
							width='50px' /></li>

					</ul>


					{% else %}

					<ul class="nav pull-right">
						<li><a href="{{ url_for('accounts_app.login') }}"> Login
						</a></li>
						<li><a href="{{ url_for('accounts_app.signup') }}">
								Signup </a></li>
					</ul>

					{% endif %}

				</div>

			</div>
		</div>
	</div>

	{% if g.user %} {% if g.tweet %}
	<div class="row-fluid">
		<div class='span1'></div>
		<div class='span2' title="Amount of labeled tweets.">
			<img src="/static/img/twitter.png" width='50px' /> {% if
			g.statistic%} <font color="#00adff"> <b>{{
					g.statistic.count }}</b></font> {%else %} <font color="#00adff"> <b>0</b></font>
			{% endif %}
		</div>
		<div class='span9' title="Goal to be achieved.">
			<img src="/static/img/goal.png" width='50px' /> {% if g.statistic%}
			<font color="#00adff"> <b>{{ g.statistic.goal.count }}</b></font>
			{%else %} <font color="#00adff"> <b>0</b></font> {% endif %}
		</div>
	</div>
	{% endif%} {% endif%}

	<div class="container">
		{% with messages = get_flashed_messages(with_categories=true) %}
		<div id="messages">
			{% for category, message in messages %}
			<div class="alert alert-{{ category }}">
				<a class="close" data-dismiss="alert">&times;</a> <strong>{{
					message }}</strong>
			</div>
			{% endfor %}
		</div>
		{% endwith %} {% block content %}{% endblock %}
	</div>
	<!-- /container -->

	<!-- Le javascript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script
		src="{{ url_for('static', filename='js/jquery-1.10.1.min.js') }}"></script>
	<script
		src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
	{% block extrajs %}{% endblock %}

	<!-- <br />
	<br />
	<br />
	<br /> -->
	<div class="container">
		<div class="row-fluid">
			<div class="span3">
				<center>
					<a href="http://www.eubra-bigsea.eu/" target="blank">
						<img src='/static/img/big_sea.jpg' width='90%' />
					</a>
				<center />
			</div>
			<div class="span6"></div>
			<div class="span3">
				<center>
					<a href="https://www.ufmg.br/" target="blank">
						<img src='/static/img/ufmg.jpg' width='90%' />
					</a>
				<center />
			</div>
		</div>
	</div>
</body>
<script src="/static/js/jscolor.js"></script>
<script src="/static/js/jquery-1.10.1.min.js"></script>
<script>
	$(document).ready(function(){
		$('#color-select').on('change', function(e){
			
			var elem = $('[name="colors"]');
			elem.val(elem.val() + $(this).val() + ";");
		})
	});
</script>
</html>

gui/portal/templates/form_macro.html
{% macro form_field(field) -%}
    {% set with_label = kwargs.pop('with_label', False) %}
    {% set placeholder = '' %}
    {% if not with_label %}
        {% set placeholder = field.label.text %}
    {% endif %}
    <div class="control-group {% if field.errors %}error{% endif %}">
        {% if with_label %}
            <label for="{{ field.id }}" class="control-label">
                {{ field.label.text }}{% if field.flags.required %} *{% endif %}:
            </label>
        {% endif %}
        <div class="controls">
            {% set class_ = kwargs.pop('class_', '') %}
            {% if field.flags.required %}
                {% set class_ = class_ + ' required' %}
            {% endif %}
            {% if field.type == 'BooleanField' %}
                <label class="checkbox">
                    {{ field(class_=class_, **kwargs) }}
                    {{ field.label.text|safe }}
                </label>
            {% else %}
            	
                {% if field.type in ('TextField', 'TextAreaField', 'PasswordField') %}
                    {% set class_ = class_ + ' input-xlarge' %}
                {% elif field.type == 'FileField' %}
                    {% set class_ = class_ + ' input-file' %}
                {% endif %}
                {{ field(class_=class_, placeholder=placeholder, **kwargs) }}
            {% endif %}
            {% if field.errors %}
                <span class="error help-inline">{{ field.errors|join(', ') }}</span>
            {% endif %}
            {% if field.description %}
                <p class="help-block">{{ field.description|safe }}</p>
            {% endif %}
        </div>
    </div>
{%- endmacro %}

gui/portal/templates/pagination_macro.html
{% macro render_pagination(pagination) %}
  <div class="pagination pagination-large">
    <ul>
  {%- for page in pagination.iter_pages() %}
    {% if page %}
      {% if page != pagination.page %}
        <li><a href="{{ request.base_url }}?page={{ page }}">{{ page }}</a></li>
      {% else %}
        <li class="active"><a href="#">{{ page }}</a></li>
      {% endif %}
    {% else %}
      <li class="disabled"><span class=ellipsis>…</span></li>
    {% endif %}
  {%- endfor %}
    </ul>
  </div>
{% endmacro %}