gui/portal/accounts/forms.py
# -*- coding: utf-8 -*-
'''
Created on Dec/2016

@author: Zilton Cordeiro Junior
@github: https://github.com/zilton
@project: EUBRA-BIGSEA
@task: Active Learning System
'''

from flask import render_template, current_app
from wtforms import *
from flask.ext.wtf import Form
from flask_mail import Message

from application import mail
from common.utils import get_signer
from accounts.models import User


class LoginForm(Form):

    user = None

    username = TextField(
        label=u'Login',
        validators=[
            validators.required()
        ]
    )

    password = PasswordField(
        label=u'Password',
        validators=[
            validators.required()
        ]
    )

    next = HiddenField()

    def validate_username(form, field):
        username = field.data
        try:
            form.user = User.objects.get(username=username)
        except:
            raise ValidationError(u'Login not found.')

    def validate_password(form, field):
        password = field.data
        if form.user:
            if not form.user.check_password(password):
                raise ValidationError(u'Incorrect password.')


class SignupForm(Form):

    email = TextField(
        label=u'E-mail',
        validators=[
            validators.required(),
            validators.length(max=100),
            validators.Email()
        ]
    )

    def validate_email(form, field):
        email = field.data
        if User.objects.filter(email=email):
            raise ValidationError(u'E-mail in use.')

    def save(self):
        email = self.email.data
        site_name = current_app.config['PROJECT_SITE_NAME']
        site_url = current_app.config['PROJECT_SITE_URL']
        sender = current_app.config['MAIL_DEFAULT_SENDER']

        # create signed data
        s = get_signer()
        data = {
            'email': email,
            'signup': True
        }
        signed_data = s.dumps(data)

        # set context to template render
        context = dict(
            site_name=site_name,
            site_url=site_url,
            email=email,
            signed_data=signed_data
        )

        # load template
        html = render_template(
            'accounts/emails/signup.html', **context
        )

        # create and send message
        msg = Message(
            u'Confirm your account - {0}.'.format(site_name),
            sender=sender,
            recipients=[email]
        )
        msg.html = html
        mail.send(msg)


class SignupConfirmForm(Form):

    name = TextField(
        label=u'Name',
        validators=[
            validators.required(),
            validators.length(max=100)
        ]
    )

    username = TextField(
        label=u'Login',
        validators=[
            validators.required(),
            validators.length(min=3, max=30),
            validators.Regexp(
                regex=r'^[\w]+$',
                message=u'Just letters and numbers.'
            )
        ]
    )
    
    institution = TextField(
        label=u'Institution',
        validators=[
            validators.required(),
            validators.length(max=100)
        ]
    )

    password = PasswordField(
        label=u'Password',
        validators=[
            validators.required(),
            validators.length(min=6, max=16)
        ]
    )

    password_confirm = PasswordField(
        label=u'Password Confirm',
        validators=[
            validators.required()
        ]
    )

    next = HiddenField()

    def validate_username(form, field):
        username = field.data
        if User.objects.filter(username=username):
            raise ValidationError(u'Login in use.')

    def validate_password_confirm(form, field):
        password = form.password.data
        password_confirm = field.data
        if password != password_confirm:
            raise ValidationError(u'Incorrect password.')

    def save(self, email):
        name = self.name.data
        username = self.username.data
        password = self.password.data
        email = email
        institution = self.institution.data

        user = User(name=name, username=username, password=password, email=email, institution=institution)
        user.save()
        return user


class RecoverPasswordForm(Form):

    email = TextField(
        label=u'E-mail',
        validators=[
            validators.required(),
            validators.length(max=100),
            validators.Email()
        ]
    )

    def validate_email(form, field):
        email = field.data
        if not User.objects.filter(email=email):
            raise ValidationError(u'E-mail not found.')

    def save(self):
        email = self.email.data
        site_name = current_app.config['PROJECT_SITE_NAME']
        site_url = current_app.config['PROJECT_SITE_URL']
        sender = current_app.config['MAIL_DEFAULT_SENDER']

        # create signed data
        s = get_signer()
        data = {
            'email': email,
            'recover-password': True
        }
        signed_data = s.dumps(data)

        # set context to template render
        context = dict(
            site_name=site_name,
            site_url=site_url,
            email=email,
            signed_data=signed_data
        )

        # load template
        html = render_template(
            'accounts/emails/recover_password.html', **context
        )

        # create and send message
        msg = Message(
            u'Recover your password - {0}.'.format(site_name),
            sender=sender,
            recipients=[email]
        )
        msg.html = html
        mail.send(msg)


class RecoverPasswordConfirmForm(Form):

    password = PasswordField(
        label=u'Password',
        validators=[
            validators.required(),
            validators.length(min=6, max=16)
        ]
    )

    password_confirm = PasswordField(
        label=u'Password Confirm',
        validators=[
            validators.required()
        ]
    )

    def validate_password_confirm(form, field):
        password = form.password.data
        password_confirm = field.data
        if password != password_confirm:
            raise ValidationError(u'Incorrect password.')

    def save(self):
        password = self.password.data
        self.user.set_password(password)
        self.user.save()
        return self.user

gui/portal/accounts/views.py
# -*- coding: utf-8 -*-
'''
Created on Dec/2016

@author: Zilton Cordeiro Junior
@github: https://github.com/zilton
@project: EUBRA-BIGSEA
@task: Active Learning System
'''

from flask import (
    Blueprint, render_template, session, g, flash, request, redirect, url_for,
    current_app
)
from accounts.models import User, Control
from accounts.forms import (
    LoginForm, SignupForm, SignupConfirmForm, RecoverPasswordForm,
    RecoverPasswordConfirmForm
)
from common.utils import get_signer
from flask_mail import Message
from application import mail
import hashlib

accounts_app = Blueprint('accounts_app', __name__)


@accounts_app.before_app_request
def load_user():
    g.user = None
    
    if 'user_id' in session:
        try:
            g.user = User.objects.get(pk=session['user_id'])
            
            m = hashlib.md5()
            m.update(g.user.email.encode('utf8'))
            g.hash = m.hexdigest()
        except:
            pass


@accounts_app.route('/login/', methods=['GET', 'POST'])
def login():
    next = request.values.get('next', '/')
    form = LoginForm()
    form.next.data = next
    if form.validate_on_submit():
        session['user_id'] = unicode(form.user.pk)
        flash(u'Login successfully', 'success')
        
        g.user = User.objects.get(pk=session['user_id'])
        sha1 = hashlib.sha1()
        sha1.update(g.user.email.encode('utf8'))
        g.hash = sha1.hexdigest()
        return redirect(next)
    return render_template('accounts/login.html', form=form)


@accounts_app.route('/logout/')
def logout():
    next = request.args.get('next', '/')
    flash(u'Logout successfully', 'success')
    session.pop('user_id', None)
    return redirect(next)


@accounts_app.route('/signup/', methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        form.save()
        flash(
            u'Check your email to confirm registration.',
            'success'
        )
        return redirect(url_for('pages_app.index'))
    return render_template('accounts/signup.html', form=form)


@accounts_app.route('/signup/<token>/', methods=['GET', 'POST'])
def signup_confirm(token):
    s = get_signer()
    try:
        signed_data = s.loads(
            token, max_age=current_app.config['PROJECT_SIGNUP_TOKEN_MAX_AGE']
        )
        email = signed_data['email']
        signup = signed_data['signup']
    except:
        flash(u'Invalid activation Link.', 'error')
        return redirect(url_for('accounts_app.signup'))

    if User.objects.filter(email=email):
        flash(u'E-mail in use.', 'error')
        return redirect(url_for('accounts_app.signup'))

    next = request.values.get('next', '/')

    form = SignupConfirmForm()
    form.next.data = next
    if form.validate_on_submit():
        user = form.save(email=email)
        session['user_id'] = unicode(user.pk)
        flash(u'Account registered successfully.', 'success')
        return redirect(next)
    return render_template('accounts/signup_confirm.html', form=form, token=token)


@accounts_app.route('/recover-password/', methods=['GET', 'POST'])
def recover_password():
    form = RecoverPasswordForm()
    if form.validate_on_submit():
        form.save()
        flash(
            u'Check it out at your email instructions for setting a new password.',
            'success'
        )
        return redirect(url_for('pages_app.index'))
    return render_template('accounts/recover_password.html', form=form)

@accounts_app.route('/information/', methods=['GET', 'POST'])
def information():
    g.user = None
    
    if 'user_id' in session:
        
        try:
            g.user = User.objects.get(pk=session['user_id'])
        except:
            pass
        
    return render_template('accounts/information.html')


@accounts_app.route('/manager/', methods=['GET', 'POST'])
def selet():
    g.user = None
    
    if 'user_id' in session:
        try:
            g.user = User.objects.get(pk=session['user_id'])
            if g.user.is_superuser:
                g.all_users = User.objects.get()
            else:
                g.all_users = None                   
        except:
            pass
        
    return render_template('accounts/selet.html')

@accounts_app.route('/manager/users', methods=['GET', 'POST'])
def manager_user():
    g.user = None
    
    if 'user_id' in session:
        try:
            g.user = User.objects.get(pk=session['user_id'])
            if g.user.is_superuser:
                g.all_users = User.objects.filter()
                g._user_label = ["Name", "Login" ,"e-mail", "Institution", "Projects" ,"Active", "Admin", "Remove"]
                g._user_value = []
                #for u in g.all_users:
                    #g._user_value.append([u.name, u.username, u.email, u.is_active, u.is_superuser, "Remove"])
            else:
                g.all_users = None
        except:
            pass
        
    return render_template('accounts/manager_user.html')

@accounts_app.route('/manager/users/change-active/<active>/<username>')
def change_active(active, username):
    g.user = None
    
    if 'user_id' in session:
        try:
            g.user = User.objects.get(pk=session['user_id'])
            if g.user.is_superuser:
                if active == "True":
                    active = True
                else:
                    active = False
                user_to_change = User.objects.filter(username=username).first()
                print user_to_change.username
                user_to_change.is_active = active
                user_to_change.change_active(is_active=active)
        except:
            pass
        
    return redirect(url_for('accounts_app.manager_user'))

@accounts_app.route('/manager/users/change-superuser/<superuser>/<username>')
def change_admin(superuser, username):
    g.user = None
    
    if 'user_id' in session:
        try:
            g.user = User.objects.get(pk=session['user_id'])
            if g.user.is_superuser:
                if superuser == "True":
                    superuser = True
                else:
                    superuser = False
                
                user_to_change = User.objects.filter(username=username).first()
                user_to_change.is_superuser = superuser
                user_to_change.change_superuser(is_superuser=superuser)
                flash(u'The admin privileges for the user %s was changed successfully.' % username, 'success')
                
                new_admin = User.objects.filter(username=username).first()
                
                if superuser and new_admin.is_superuser:
                    try:
                        site_name = current_app.config['PROJECT_SITE_NAME']
                        site_url = current_app.config['PROJECT_SITE_URL']
                        sender = current_app.config['MAIL_DEFAULT_SENDER']
                        # set context to template render
                        context = dict(
                            site_name=site_name,
                            site_url=site_url,
                            assign_by=g.user.name,
                            new_admin_name=new_admin.name
                        )
                        # load template
                        html = render_template(
                            'accounts/emails/admin_confirmation.html', **context
                        )
                        # create and send message
                        msg = Message(
                            u'Confirmation - admin privileges - {0}.'.format(site_name),
                            sender=sender,
                            recipients=[new_admin.email]
                        )
                        msg.html = html
                        mail.send(msg)
                    except:
                        flash(u"Was not possible to send a confirmation by e-mail for the user %s." % new_admin.name, 'error')
            else:
                flash(u"You do not have permission!", 'error')
        except:
            flash(u'Was not possible to assign the admin privileges for the user %s.' % username, 'success')
    
    return redirect(url_for('accounts_app.manager_user'))

@accounts_app.route('/manager/users/remove-user/<username>')
def remove_user(username):
    g.user = None
    if 'user_id' in session:
        try:
            g.user = User.objects.get(pk=session['user_id'])
            if g.user.is_superuser:
                user_to_change = User.objects.filter(username=username).first()
                if not g.user.username == user_to_change.username:
                    user_to_change.delete()
        except:
            pass
        
    return redirect(url_for('accounts_app.manager_user'))

@accounts_app.route('/recover-password/<token>/', methods=['GET', 'POST'])
def recover_password_confirm(token):
    s = get_signer()
    try:
        signed_data = s.loads(
            token, max_age=current_app.config['PROJECT_RECOVER_PASSWORD_TOKEN_MAX_AGE']
        )
        email = signed_data['email']
        recover_password = signed_data['recover-password']
    except:
        flash(u'Invalid Link.', 'error')
        return redirect(url_for('pages_app.index'))

    try:
        user = User.objects.get(email=email)
    except:
        flash(u'E-mail not found.', 'error')
        return redirect(url_for('pages_app.index'))

    form = RecoverPasswordConfirmForm()
    form.user = user
    if form.validate_on_submit():
        user = form.save()
        flash(u'Password set successfully.', 'success')
        return redirect(url_for('accounts_app.login'))
    return render_template(
        'accounts/recover_password_confirm.html',
        form=form, token=token, user=user
    )

@accounts_app.route('/accounts/admin-privileges/', methods=['GET', 'POST'])
def requests_admin_privileges():
    if 'user_id' in session:
        try:

gui/portal/templates/accounts/information.html
{% extends 'base.html' %}
{% block title %}Information{% endblock %}
{%block content %}
	{% if g.user %}
		
			  <h1><font color="#00adff">User information</font></h1>
			  <br/><br/>
			  <font size=4>
			  <strong>Name: </strong>{{g.user.name}}<br/><br/>
			  <strong>Email: </strong>{{g.user.email}}<br/><br/>
			  <strong>Institution: </strong>{{g.user.institution}}<br/><br/>
			  <strong>Username: </strong>{{g.user.username}}<br/><br/>
			  <a href="https://en.gravatar.com/gravatars/new/computer" target="_blank"><button type="button" class="btn btn-primary">Change photo</button></a><br/><br/>
			  <a href="/recover-password"><button type="button" class="btn btn-primary">Change password</button></a><br/><br/>
			  {% if not g.user.is_superuser %}
			  	<a href="{{url_for('accounts_app.requests_admin_privileges')}}"><button type="button" class="btn btn-warning">Request admin privileges</button></a><br/><br/>
			  {% endif %}
			  <br/><br/>
			  <br/><br/>
	
	{% endif%}
{% endblock %}

gui/portal/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}

<div class="page-header">
  <h3>Login</h3>
</div>

<form action="{{ url_for('accounts_app.login') }}" method="post" class="form-horizontal">
  {{ form.hidden_tag() }}
  {% import 'form_macro.html' as form_macro %}
  {{ form_macro.form_field(form.username, with_label=True) }}
  {{ form_macro.form_field(form.password, with_label=True) }}
  <div class="form-actions">
    <button type="submit" class="btn btn-icon btn-primary">Send</button>
    <a href="{{ url_for('accounts_app.recover_password') }}" class="btn btn-link">Forgot Password?</a>
  </div>
</form>

{% endblock %}

gui/portal/templates/accounts/manager_user.html
{% extends 'base.html' %}
	{% block title %}Dashboard{% endblock %}
		{%block content %}
			{% if g.user.is_superuser %}
				<h1>
					<center><font color="#00adff">Users</font><center />
				</h1>
				<br/><br/>
				
				<table class="table table-striped">
					<thead>
						<tr>
							{% for label in g._user_label %}
							<th>
								<font color="black"><center>{{label}}</center></font>
							</th> {% endfor %}
						</tr>
					</thead>

					<tbody>
						<tr>
							{% for user in g.all_users %}
								<tr>
									<td>
										<center>
											<font><b>{{user.name}}</b></font>
										</center>
									</td>
									<td>
										<center>
											<font><b>{{user.username}}</b></font>
										</center>
									</td>
									<td>
										<center>
											<font><b>{{user.email}}</b></font>
										</center>
									</td>
									<td>
										<center>
											<font><b>{{user.institution}}</b></font>
										</center>
									</td>
									<td>
										<center>
											<select>
											{% for p in user.control.projects %}
												<option value={{p}}>{{p}}</option>
											{% endfor %}
											</select>
										</center>
								    </td>
									<td>
										<center>
											<a
												href="{{url_for('accounts_app.change_active', active=not user.is_active, username=user.username) }}">
												{% if user.is_active %}
													<input class="btn btn-success" type="submit" name="submit" value={{user.is_active}} title="Turn {{not user.is_active}} - the access for the user {{user.name}}">
												{% else %}
													<input class="btn btn-danger" type="submit" name="submit" value={{user.is_active}} title="Turn {{not user.is_active}} - the access for the user {{user.name}}">
												{% endif %}
											</a>
										</center>
									</td>
									<td>
										<center>
											<a href="{{url_for('accounts_app.change_admin', superuser=not user.is_superuser, username=user.username) }}">
												{% if user.is_superuser %}
													<input class="btn btn-success" type="submit" name="submit" value="{{user.is_superuser}} " title="Turn {{ not user.is_superuser }} - the admin privileges for the user {{user.name}}">
												{% else %}
													<input class="btn btn-danger" type="submit" name="submit" value={{user.is_superuser}} title="Turn {{ not user.is_superuser }} - the admin privileges for the user {{user.name}}">
												{% endif %}
											</a>
										</center>
									</td>	
									<td>
										<center>
											<a
												href="{{url_for('accounts_app.remove_user', username=user.username) }}" class="confirmation">
												<input type="image" src="/static/img/remove.png" style="width:10%;" title="Remove the user {{ user.name }}">
											</a>
										</center>
									</td>	
								</tr>
								<p></p>
							{% endfor %}
						</tr>
						<script type="text/javascript">
						    var elems = document.getElementsByClassName('confirmation');
						    var confirmIt = function (e) {
						        if (!confirm('Are you sure?')) e.preventDefault();
						    };
						    for (var i = 0, l = elems.length; i < l; i++) {
						        elems[i].addEventListener('click', confirmIt, false);
						    }
						</script>
					</tbody>
				</table>
				<br />
				<br />
				<br />
				<br />
				<br />
				<br />
			{% endif%}
		{% endblock %}
			

gui/portal/templates/accounts/recover_password.html
{% extends 'base.html' %}

{% block title %}Forgot Password{% endblock %}

{% block content %}

<div class="page-header">
  <h3>Change Password</h3>
</div>

<form action="{{ url_for('accounts_app.recover_password') }}" method="post" class="form-horizontal">
  {{ form.hidden_tag() }}
  {% import 'form_macro.html' as form_macro %}
  {{ form_macro.form_field(form.email, with_label=True) }}
  <div class="form-actions">
    <button type="submit" class="btn btn-icon btn-primary">Send</button>
  </div>
</form>

{% endblock %}

gui/portal/templates/accounts/recover_password_confirm.html
{% extends 'base.html' %}

{% block title %}Set new password for login {{ user.username }}{% endblock %}

{% block content %}

<div class="page-header">
  <h3>Set new password for login {{ user.username }}</h3>
</div>

<form action="{{ url_for('accounts_app.recover_password_confirm', token=token) }}" method="post" class="form-horizontal">
  {{ form.hidden_tag() }}
  {% import 'form_macro.html' as form_macro %}
  {{ form_macro.form_field(form.password, with_label=True) }}
  {{ form_macro.form_field(form.password_confirm, with_label=True) }}
  <div class="form-actions">
    <button type="submit" class="btn btn-icon btn-primary">Send</button>
  </div>
</form>

{% endblock %}

gui/portal/templates/accounts/selet.html
{% extends 'base.html' %}
	{% block title %}Dashboard{% endblock %}
		{%block content %}
			{% if g.user.is_superuser %}
				<h1>
					<center><font color="#00adff">Select the page for managing</font><center />
				</h1>
				<br/><br/>
			  <br/><br/>
				<div class="container">
					<div class="row-fluid">
					<div class="span3"></div>
						<div class="span3">
							<center>
								<a href="{{ url_for('system_app.new_project') }}"><img src='/static/img/dashboard.ico' width='20%' title="System manager"/></a> 
								<center />
						</div>
						
						<div class="span3">
							<center>
								<a href="{{ url_for('accounts_app.manager_user') }}"><img src='/static/img/users.png' width='20%' title="User manager"/></a> 
								<center />
						</div>
						<div class="span3"></div>
					</div>
				</div>
			  <br/><br/>
			  <br/><br/>
			  <br/><br/>
			  <br/><br/>
			{% endif%} {% endblock %}
			
<!-- 
			  <br/><br/>
			  <a
					href="{{url_for('accounts_app.manager', sentiment='positive', _id=g.tweet._id) }}">
					<input class="btn btn-success" type="checkbox" name="submit" value="true">
				</a>
			  <font size=4>
			  <strong>Name: </strong>{{g.user.name}}<br/><br/>
			  <strong>Email: </strong>{{g.user.email}}<br/><br/>
			  <strong>Username: </strong>{{g.user.username}}<br/><br/>
			  <a href="https://en.gravatar.com/gravatars/new/computer" target="_blank"><button type="button" class="btn btn-primary">Change photo</button></a><br/><br/>
			  <a href="/recover-password"><button type="button" class="btn btn-primary">Change password</button></a><br/><br/>
			  <br/><br/>
			  <br/><br/> -->

gui/portal/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}Signup{% endblock %}

{% block content %}

<div class="page-header">
  <h3>Signup</h3>
</div>

<form action="{{ url_for('accounts_app.signup') }}" method="post" class="form-horizontal">
  {{ form.hidden_tag() }}
  {% import 'form_macro.html' as form_macro %}
  {{ form_macro.form_field(form.email, with_label=True) }}
  <div class="form-actions">
    <button type="submit" class="btn btn-icon btn-primary">Send</button>
    <a href="/recover-password">Forgot password</a>
  </div>
</form>

{% endblock %}

gui/portal/templates/accounts/signup_confirm.html
{% extends 'base.html' %}

{% block title %}Confirm Signup{% endblock %}

{% block content %}

<div class="page-header">
  <h3>Confirm Signup</h3>
</div>

<form action="{{ url_for('accounts_app.signup_confirm', token=token) }}" method="post" class="form-horizontal">
  {{ form.hidden_tag() }}
  {% import 'form_macro.html' as form_macro %}
  {{ form_macro.form_field(form.name, with_label=True) }}
  {{ form_macro.form_field(form.username, with_label=True) }}
  {{ form_macro.form_field(form.institution, with_label=True) }}
  {{ form_macro.form_field(form.password, with_label=True) }}
  {{ form_macro.form_field(form.password_confirm, with_label=True) }}
  <div class="form-actions">
    <button type="submit" class="btn btn-icon btn-primary">Send</button>
  </div>
</form>

{% endblock %}